### ISSUE TITLE
Support for icon / image next to header

### ISSUE THREAD

**Issue by modplug** [Cheesebaron/SGTabbedPager#14]
I would like to have the possibility to add a icon / image next to the header. 
Left or right to the text. Maybe even a badge with a numeric value

**Comment by Cheesebaron** [comment]
Will have a look at this soon :)

**Comment by Cheesebaron** [comment]
Do you have any ideas on how you want the badge to look?

**Comment by modplug** [comment]
Great work! I guess this can be closed now 👍
