### ISSUE TITLE
can it be placed on the bottom

### ISSUE THREAD

**Issue by jorgenstorlie** [Cheesebaron/SGTabbedPager#2]
Is it possible to place in on the bottom of the screen?

**Comment by Cheesebaron** [comment]
Sure, just change these constraints: https://github.com/Cheesebaron/SGTabbedPager/blob/master/SGTabbedPager/SGTabbedPager.cs#L97

**Comment by Cheesebaron** [comment]
Fixed in 1.1.0, see #11
