### ISSUE TITLE
Custom TitleScrollView leading and trailing space

### ISSUE THREAD

**Issue by KanLei** [Cheesebaron/SGTabbedPager#6]
I want custom the leading and trailing space on titlescrollview,  so titlescrollview content more compact, where should I change?

**Comment by Cheesebaron** [comment]
The height is determined by: https://github.com/Cheesebaron/SGTabbedPager/blob/master/SGTabbedPager/SGTabbedPager.cs#L27

if you want other spacing you will have to add margins to the View Constraints: https://github.com/Cheesebaron/SGTabbedPager/blob/master/SGTabbedPager/SGTabbedPager.cs#L162

**Comment by KanLei** [comment]
@Cheesebaron Thank you, I could explain more detailedly. I want to remove redundant space or custom the space of TitleScrollView content size, like this "|-custom space-[title1]-space-[title2]-space-[title3]-custom space-|", so the first title should be left of the TitleScrollView and the last title should be right of TitleScrollView, but there are some code confuse me, like this
https://github.com/Cheesebaron/SGTabbedPager/blob/master/SGTabbedPager/SGTabbedPager.cs#L358
I want to achieve mainstream TitleScrollView.
![Uploading webwxgetmsgimg.jpg…]()

**Comment by Cheesebaron** [comment]
https://github.com/Cheesebaron/SGTabbedPager/blob/master/SGTabbedPager/SGTabbedPager.cs#L313 if you want to change the spacing then change the 30 value here.

**Comment by KanLei** [comment]
@Cheesebaron Yes, I have tried this. And I think I should change the code below "if(i == 0) " to "currentX += 30", and the "if (i == _viewControllerCount - 1)".... This works only when first launch the scrollview, but when I selected the titlescrollview or scroll the contentscrollview, there are some other code will change this. Maybe the code I have mentioned above. So there are many code position the  titlescrollview, but I am not understand completely.
![example](https://cloud.githubusercontent.com/assets/3018288/11653295/23c43134-9dd8-11e5-8578-7013d3e9fe5f.png)

**Comment by Cheesebaron** [comment]
Sorry, I don't understand what you do not understand. You are not making yourself clear.

**Comment by KanLei** [comment]
@Cheesebaron Sorry about my poor english. I want that selected title item not always center in the titlescrollview. So the first select item should be on the left, not the center.^_^

**Comment by MrBasque** [comment]
Exactly what I am looking for too :) Any updates on this?

**Comment by Cheesebaron** [comment]
Nope. Pull Requests are welcome.

**Comment by david6p2** [comment]
Yes, I want to do the same. I just have 3 items, but as soon as the Pager is loaded, you see the first title on the center and the second on the right and the third is not visible. I would like to have all of the 3 titles visible without scrolling and add scrolling only if the number of titles is greater than 4 or if the size of the titles width is greater than the container view width

**Comment by BatriderLEL** [comment]
@david6p2 yeah,i want the same. 

that the idea to have similar of this 
![r7t0uyj](https://cloud.githubusercontent.com/assets/25818124/23849143/098eaa6c-07e3-11e7-8c47-91b0b4852ff2.jpg) . 

or like this  : 

![0-njntjk_zesa2wh9r](https://cloud.githubusercontent.com/assets/25818124/23849300/b8a1667a-07e3-11e7-9afe-113c50d1ef8a.jpg)

**Comment by Cheesebaron** [comment]
As I have said. Pull Requests are welcome :)

I am not dismissive of these suggestions to mage the pager configurable, but this stuff takes time to implement and make sure looks good on all screen sizes.


@BatriderLEL I don't see how the last screenshot you posted is different from what currently is covered by the library, when you have the middle item selected, it looks exactly like that.
However, the first screen shot is obviously different and has potential to be implemented.

**Comment by BatriderLEL** [comment]
@Cheesebaron Hi. Thanks for the fast reply. So as you can see, the main idea is to disable this "scrollview" and put title in static position.

I tried to show it manually,so after switching to another tab, the title area needs to remain static as it shows here : 
![whatweneed](https://cloud.githubusercontent.com/assets/25818124/23890477/b89aeb1c-089a-11e7-8889-f3b6c051f05e.gif)

> However, the first screen shot is obviously different and has potential to be implemented.  

OK, can you tell us,how we can achieve this setup ? Lets do an additional configuration, for e.g. : if you need this static behaviour, then for property that called "StaticTitile" put "true" and it activates static title w/o scroll.

As i showed before,that our concept : 

![r7t0uyj](https://cloud.githubusercontent.com/assets/25818124/23849143/098eaa6c-07e3-11e7-8c47-91b0b4852ff2.jpg) . 

I think it's a good idea to have this in component, also i can try to do that(but unfortunately  i have poor skills in Xamarin.iOS :( , anyway i want to help and lets do a pull request :) ).

**Comment by KanLei** [comment]
For people who want to custom the `TitleScrollView` layout. First, you can adjust the title position in **Layout** method, codes like `label.Frame` for initial position, then update `TitleScrollView.SetContentOffset` in **SwitchPage** and **Scrolled** methods when scrolled to meet your needs. I custom this for my requirement. Hope this help.
