### ISSUE TITLE
Can you provide a working example for the MvxSGTabbedPager implementation?

### ISSUE THREAD

**Issue by MrBasque** [Cheesebaron/SGTabbedPager#8]
Will this work with MvvmCross CreateBindingSet() etc?

**Comment by MrBasque** [comment]
Will this work with MvvmCross CreateBindingSet() etc?

**Comment by Cheesebaron** [comment]
Well it doesn't have a TargetBinding, so I understand that it is not entirely clear how to use it.

I've just added a sample project for you to try out and look in :) https://github.com/Cheesebaron/SGTabbedPager/tree/master/SampleMvx

**Comment by MrBasque** [comment]
Wow Thanks @Cheesebaron!, Will have a look!

**Comment by MrBasque** [comment]
Great stuff, thanks for the effort!
